# Below parameters are tested on Cornelia's computer in PCC by Yanko and me and worked successfully.
# We could only record from 2 cameras, as we had only 2 cameras with the exact same model I have used before (firmware is different for different versions of the same model)

# Video parameters
videoFolder: 'C:\Users\facial\Desktop\record\test_recordings_campy'
videoFilename: 'first_test_2cams.mp4'
frameRate: 60 # last test: 21 fps max!
recTimeInSec: 20

# Camera parameters
numCams: 2
cameraSelection: [0,1]  # selects which cameras are used and in which order
cameraNames: ["Cam_A","Cam_B"]
cameraSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
cameraMake: "flir"
pixelFormatInput: "gray"  # 'bayer_bggr8', 'gray', 'rgb24', 'bgr0', 'yuv420p'
pixelFormatOutput: "gray"

# FLIR camera settings (options can be checked from Spinnaker SDK, not every option is implemented!)
exposureTimeInUs: 10000  # In microseconds
gain: 5  # 0-40
bufferMode: "OldestFirst"  # First in, first out
bufferSize: 10  # 10-100. Don't set this to more than 100. Even tho the camera max is much higher, it doesn't work (probably a bug of Spinnaker)
disableGamma: True  # Gamma correction is not recommended for scientific purposes
grabTimeOutInMilliseconds: 10000

# Compression parameters
ffmpegLogLevel: "quiet"   # "quiet", "warning", "info"
gpuID: [0,0]         # -1 = CPU, GPU id for Nvidia multi-GPU, default is 0
gpuMake: "nvidia"         # "nvidia", "amd", "intel"
codec: "h264"             # "h264", "h265", or user-defined video codec
quality: "21"             # 0-55

# Display parameters
chunkLengthInSec: 10
displayFrameRate: 5
displayDownsample: 4

# Other parameters
ffmpegPath: 'C:\Users\facial\Downloads\ffmpeg-4.1.4-win64-static\bin\ffmpeg.exe' # The codebase needs an older version of ffmpeg, doesn't work with v6
frameWidth: 2448  # max:2448, 75%:1836
frameHeight: 2048  # max:2048, 75%:1536
